worlds:
    sgc1:
    - APRGL3SCJ
    - X4SHLCGBY
    - 4IQ1T5XXC
    - 23OZ1MKSF
    - A3XXPIIIG
    - QZWKEH0AB
    - QJMTX8EBJ
    - AJFYFLGEC
    - 55CP8WO8W
    - MO30ML2KA
    - ZSAV45W6W
    - MMG355FFN
    - O9Y3I6B7O
    - NZOABXAET
    - 8DYD337DB
    - EWRCAW4Z4
    - CZPQPPWYN
    - 1SR97N743
    build test1:
    - ZEAZEQI4L
    build test:
    - BDNVX78WU
    - 3EMMVEK6B
    sg2:
    - EAJP0KLMC
    - U4JR2QIU1
    - 0A1F82I98
    - 3JP22Z6TT
    - ZOVYSP4T9
    - 6ZZ0Q4OLG
    - ONN68S089
    sg50:
    - 0GTMIZKNV
    - U4IQ2RK1R
    - AA2OAV974
