name = "Kaio Yuuji - Stargate Galaxy"
author = "Kaio Yuuji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c9f0904e01a011610d11d100d0e61f00e45e2135b882d451fb3178702a290a8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
